# Generated by Django 4.1.3 on 2022-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accauntant', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
